import {
  ArrowRight,
  AlertTriangle,
  BookOpen,
  Camera,
  CheckCircle,
  Clock,
  DollarSign,
  FileText,
  Gavel,
  GitBranch,
  Heart,
  Home,
  Laptop,
  Mail,
  MessageSquare,
  Search,
  Shield,
  Star,
  Target,
  Users,
  Zap,
} from "lucide-react";

export const RULE_CATEGORIES = [
  {
    id: "A",
    label: "A. Core Operating Principles",
    icon: Star,
    color: "border-yellow-400 bg-yellow-50/30 dark:bg-yellow-950/10",
    iconColor: "bg-yellow-100 dark:bg-yellow-900/30 text-yellow-600 dark:text-yellow-400",
    summary: "The foundational mindset rules that define what success actually means in this working relationship.",
    whyItMatters: "Without these principles, task completion becomes the goal instead of burden reduction. These rules define the difference between doing work and doing work that actually helps.",
    rules: [
      "1. The goal is not only task completion; the goal is burden reduction for Robert.",
      "2. Reliability is good, but visible, timely, autonomous follow-through is what creates relief.",
      "3. If Robert still has to chase, reconstruct, clarify, or micromanage, the system has not succeeded yet.",
      "4. A task is not truly done until the result is visible, documented, linked, and usable later.",
      "5. Robert's preferred system is bottom-up: collect facts first, organize them, connect them, identify gaps, then decide.",
      "6. Do not treat progress as sufficient if deadlines are missed or evidence remains scattered.",
      "7. Work should reduce future work, not create more work later.",
      "8. Small repeated inefficiencies are serious problems when they happen daily.",
      "9. Tools, systems, and workflows should be treated like breathing: if they add friction every time, they are broken or unfinished.",
      "10. High-risk matters require prevention, not reaction.",
      "11. When Robert is overloaded, Joyce must reduce cognitive load, not add to it.",
      "12. If Robert is unclear, inconsistent, or gives conflicting instructions, Joyce should use AI to extract the conflict and ask focused clarification questions.",
      "13. When in doubt, do not silently assume. Verify, investigate, or ask Robert in yes/no format.",
      "14. Do not wait for perfect information if useful partial action can safely move the matter forward.",
      "15. If a matter affects housing, court, police, insurance, legal deadlines, evidence, or client relationships, raise its priority.",
    ],
  },
  {
    id: "B",
    label: "B. Communication Rules Between Robert and Joyce",
    summary: "Rules for how and when Joyce communicates with Robert — covering responsiveness, updates, and avoiding silence.",
    whyItMatters: "Silence creates uncertainty and forces Robert to interrupt his own work to chase status. These rules ensure communication is proactive, clear, and never leaves Robert guessing.",
    icon: MessageSquare,
    color: "border-blue-400 bg-blue-50/30 dark:bg-blue-950/10",
    iconColor: "bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400",
    rules: [
      "16. Somebody says something = reply.",
      "17. A short acknowledgement is better than silence.",
      "18. If a WhatsApp message is read, acknowledge it with a reply or reaction.",
      "19. Because read receipts are off, Joyce must manually signal that she has seen and processed important messages.",
      "20. Silence creates uncertainty and causes Robert to interrupt later.",
      "21. If Joyce sees a message late, she should still respond and explain what she will do next.",
      "22. If Joyce has a counter-suggestion, she must state it clearly instead of silently following a different plan.",
      "23. If Joyce cannot respond fully, she should send a short holding message with a time for follow-up.",
      "24. If Joyce is blocked, she must say what blocks her, what she can still do, and when she will update.",
      "25. If Joyce gives a deadline or ETA, she must update before or at that deadline.",
      "26. If Joyce misses a deadline, she must proactively explain the miss and give a recovery plan.",
      "27. Robert should not have to ask twice for the status of the same task.",
      "28. Less output with strong responsiveness is better than more output combined with silence.",
      "29. Joyce should not wait until Robert asks before sharing relevant thoughts, concerns, or feedback.",
      "30. If something affects Joyce's performance, availability, or output, Robert should be informed early.",
      "31. If Joyce's personal circumstances reduce output, she must tell Robert what can still be done and what must be postponed.",
      "32. Daily communication should be clear, concise, and actionable.",
      "33. Avoid wall-of-text updates for complex matters. Use sections, numbering, and status labels.",
      "34. When Robert asks for a brief update, give the operational facts first.",
      "35. Personal warmth is appreciated, but active tasks must still return to operational clarity.",
    ],
  },
  {
    id: "C",
    label: "C. Yes/No Decision Rules",
    summary: "How to frame decisions and requests so Robert can respond quickly with a simple yes or no.",
    whyItMatters: "Open-ended questions drain Robert's cognitive energy. A well-framed yes/no request with a recommendation lets him decide in seconds instead of minutes.",
    icon: GitBranch,
    color: "border-violet-400 bg-violet-50/30 dark:bg-violet-950/10",
    iconColor: "bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400",
    rules: [
      "36. When Robert's input is needed, Joyce should frame the issue as a yes/no decision whenever possible.",
      "37. The default format should be: recommendation + yes/no approval.",
      "38. A yes/no request may contain multiple questions if the matter is complex.",
      "39. High-risk documents do not need to be reduced to one yes/no question; they can be broken into several yes/no decisions.",
      "40. Joyce should use AI to convert unclear issues into yes/no questions for Robert.",
      "41. If Robert must decide during the workday, the question must be suitable for a quick WhatsApp answer or voice clip.",
      "42. Do not ask Robert open-ended questions when he is overloaded.",
      "43. Do not ask 'What should I do?' if Joyce can form a recommendation first.",
      "44. When Robert's approval is required, Joyce should explain the consequence of yes and no.",
      "45. If Robert does not respond, Joyce should follow up within 24 hours, or sooner if urgent.",
    ],
  },
  {
    id: "D",
    label: "D. Trello Rules",
    summary: "How to use Trello as the single source of truth — covering card updates, structure, and what belongs where.",
    whyItMatters: "If Trello is incomplete or stale, Robert cannot trust it. These rules ensure every active task is visible, traceable, and usable without needing to ask Joyce for a status.",
    icon: FileText,
    color: "border-indigo-400 bg-indigo-50/30 dark:bg-indigo-950/10",
    iconColor: "bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400",
    rules: [
      "46. Trello is the operational source of truth.",
      "47. If something matters, it belongs in Trello.",
      "48. Every card touched during the day must receive a same-day update.",
      "49. Daily Trello updates are mandatory because they make progress visible.",
      "50. A Trello update may be short, but it must be useful.",
      "51. A good Trello update states: what was done, what is next, who owns it, and what is blocked.",
      "52. If Robert's urgent attention is needed, Joyce should update the Trello card first, then send Robert the card link on WhatsApp.",
      "53. WhatsApp should point to Trello; it should not replace Trello.",
      "54. If a task is given on WhatsApp, Joyce must either act immediately or convert it into Trello.",
      "55. Every active legal, client, software, or freelancer matter should have a clear Trello card or board.",
      "56. Every Trello card involving a freelancer must show the freelancer name, role, Upwork link, current task, deadline, latest update, and blocker.",
      "57. Trello descriptions should contain the important context, not only scattered comments.",
      "58. Documents, emails, screenshots, videos, and links related to a task should be attached or linked to the Trello card.",
      "59. If external input arrives on an On-Hold task, that task can become priority over current Doing tasks.",
      "60. Done cards should receive a short completion summary.",
      "61. Large tasks should be broken into checklist items inside the card, not automatically into separate cards.",
      "62. APTLSS plans are generated by AI — click the '🎯 APTLSS Plan' button on any Trello card in the Power-Up. Do NOT add APTLSS as a checklist, description, or comment.",
      "63. If a Trello card has stale information, update the card before asking Robert to decide.",
      "64. If Robert cannot see the status in Trello, the status is not sufficiently visible.",
      "65. Cards should include waiting status: waiting on Robert, waiting on freelancer, waiting on third party, or blocked.",
      "66. Trello should show the latest follow-up date and next deadline.",
      "67. Old or scattered Trello cards should be consolidated when they refer to the same matter.",
    ],
  },
  {
    id: "E",
    label: "E. Daily and Weekly Workflow Rules",
    summary: "The recurring daily and weekly routines that keep work visible, consistent, and on track.",
    whyItMatters: "Consistency in daily routines prevents tasks from falling through the cracks. A close-out summary makes progress visible without Robert having to ask.",
    icon: Clock,
    color: "border-teal-400 bg-teal-50/30 dark:bg-teal-950/10",
    iconColor: "bg-teal-100 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400",
    rules: [
      "68. Joyce should send a daily close-out summary on workdays.",
      "69. Daily close-out should include completed, open, blocked, waiting on Robert, waiting on others, and urgent tomorrow.",
      "70. If no visible progress was made, Joyce should still report why and what the recovery plan is.",
      "71. A daily Trello update block should be scheduled, not left to chance.",
      "72. A 24-hour follow-up list should be maintained for Robert, freelancers, lawyers, clients, and third parties.",
      "73. If something was promised yesterday and not done, it must be named and recovered today.",
      "74. If Joyce works at night after her own obligations, the priorities must be clear before starting.",
      "75. When Joyce has many tasks, she should use a daily cross-card schedule, not only individual APTLSS plans.",
      "76. If one task is blocked, switch to the next useful task instead of idling.",
      "77. If waiting for an email code, response, upload, or AI output, use the waiting time for another task.",
      "78. If Robert needs the PC and Joyce is blocked, hand over the PC until Joyce can continue.",
      "79. When there are too many moving parts, make the first task an overview/status map.",
      "80. If Joyce works long hours or crunch periods, clear handovers are required before sleeping or stepping away.",
    ],
  },
  {
    id: "F",
    label: "F. Deadline and Follow-Up Rules",
    summary: "Rules for managing deadlines, following up on commitments, and converting vague timelines into concrete dates.",
    whyItMatters: "A stated timeline creates an obligation. These rules ensure that deadlines are tracked, followed up, and never silently missed — whether by Joyce, freelancers, or third parties.",
    icon: AlertTriangle,
    color: "border-orange-400 bg-orange-50/30 dark:bg-orange-950/10",
    iconColor: "bg-orange-100 dark:bg-orange-900/30 text-orange-600 dark:text-orange-400",
    rules: [
      "81. A stated timeline creates an obligation to report back.",
      "82. If Joyce says 'consider it done,' it must either be done or followed up before the deadline.",
      "83. If a freelancer promises an update, record the exact expected time.",
      "84. Vague deadlines must be converted into concrete dates or checkpoints.",
      "85. 'Third week of May' in the Dutch context should be interpreted as the third full week, not partial starting days.",
      "86. If a task is urgent/legal/client-facing, follow up sooner than 24 hours.",
      "87. If a freelancer misses a promised update, Joyce should escalate rather than wait passively.",
      "88. If an external party gives a date range, record the final day as the latest follow-up point.",
      "89. If no ETA is given, Joyce should ask for a checkpoint.",
      "90. Do not accept 'it can take some time' as a useful ETA.",
      "91. If something must be done today, same-day tracking is required.",
      "92. When Robert says 'hard deadline,' avoid words like 'I believe' or 'should.' Use confirmed deadline and escalation action.",
    ],
  },
  {
    id: "G",
    label: "G. Freelancer-Management Rules",
    summary: "How to hire, manage, track, and hold accountable the freelancers working on Robert's projects.",
    whyItMatters: "Freelancers are external and unpredictable. These rules ensure Joyce maintains control, documents everything, and escalates problems before they become costly delays.",
    icon: Users,
    color: "border-amber-400 bg-amber-50/30 dark:bg-amber-950/10",
    iconColor: "bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400",
    rules: [
      "93. Do not accept 'done' without testing the actual workflow.",
      "94. A freelancer delivery must be tested against Robert's real use case, not only a demo.",
      "95. If a freelancer says requirements are unclear, stop and create a written feature checklist.",
      "96. If a freelancer cannot run/debug the system, request a structured diagnostic report.",
      "97. A diagnostic report should include OS, repo/branch, command run, exact error, screenshots/video, .env variables, and what was tried.",
      "98. If a freelancer repeats the same blocker, require a missing-items list and next-action plan.",
      "99. Do not let freelancers create random repos, emails, or systems without approval.",
      "100. Every freelancer task should have acceptance criteria.",
      "101. Every fix should be tied to the agreed scope or original use case.",
      "102. Do not call broken agreed functionality a recommendation. Call it a fix.",
      "103. A recommendation is optional; a fix is required.",
      "104. Use precise wording with difficult freelancers to avoid scope arguments.",
      "105. If a freelancer misses one meeting, issue a warning or clear follow-up.",
      "106. If a freelancer misses two meetings, escalate and set a final appointment.",
      "107. If a freelancer misses three meetings, replacement/termination becomes the default unless Robert decides otherwise.",
      "108. If a freelancer is unavailable, update Robert immediately instead of letting the meeting silently fail.",
      "109. If a freelancer is likely to become hostile or risky, remove access before notifying them.",
      "110. Before ending a risky freelancer relationship, open all access-management pages first, then remove access rapidly.",
      "111. Remove freelancer access from GitHub, Google Drive, Trello, deployment tools, Manus, shared accounts, and any other relevant platform.",
      "112. After access removal, preserve evidence and screenshots for Upwork or dispute escalation.",
      "113. Freelancers responsible for document collation may receive temporary Drive view access if needed.",
      "114. Temporary freelancer access must be tracked and removed after the task.",
      "115. If a freelancer requires Robert's input, Joyce should filter the issue into yes/no questions first.",
      "116. Joyce should protect Robert from unnecessary freelancer back-and-forth.",
      "117. If work can be delegated without risk, Joyce should consider delegating it.",
      "118. Bulk downloads, transcriptions, uploads, renaming, and simple sorting can often be delegated.",
      "119. Legal triage, sensitive access, high-risk decisions, and Robert's decision preparation should stay closer to Joyce.",
    ],
  },
  {
    id: "H",
    label: "H. Software and Development Rules",
    summary: "Standards for managing software projects, GitHub repositories, testing, and development handovers.",
    whyItMatters: "Software without proper documentation and testing creates hidden debt. These rules ensure code is traceable, tested, and never accepted as done without verification.",
    icon: Laptop,
    color: "border-cyan-400 bg-cyan-50/30 dark:bg-cyan-950/10",
    iconColor: "bg-cyan-100 dark:bg-cyan-900/30 text-cyan-600 dark:text-cyan-400",
    rules: [
      "120. Manus is a starting/prototyping tool, not the final development environment.",
      "121. The desired path is: Manus → local code editor/version control → GitHub → local Docker deployment → usable tool.",
      "122. All code must land in the correct numbered GitHub repository.",
      "123. Project numbering must match across Manus, GitHub, Intranet, Trello, and Drive where possible.",
      "124. Do not assume a Manus thread does not exist just because the name does not match.",
      "125. Every new Manus thread should be named correctly immediately.",
      "126. Before creating new threads, inspect existing threads briefly to avoid duplicates.",
      "127. Local Docker on Robert's Windows PC is the preferred deployment target for internal tools.",
      "128. Tools should be resource-light unless a critical path truly requires speed.",
      "129. Non-urgent background actions do not need expensive or high-speed processing.",
      "130. Persistent memory/storage is required for tools that will be reused.",
      "131. A tool that loses setup after restart is not acceptable.",
      "132. A Windows-targeted tool must be tested on Windows before being presented as ready.",
      "133. A tool must be tested after logout, restart, and reopening.",
      "134. A tool must be tested with real data, not only dummy/demo data.",
      "135. Every custom tool must have step-by-step usage instructions.",
      "136. Every tool must be checked against Robert's development standards.",
      "137. If a tool requires an API token, .env variable, or credential, that dependency must be documented.",
      "138. If credentials are missing, the freelancer must list exact missing credential names.",
      "139. Random workarounds should not replace proper setup.",
      "140. A tool is not acceptable if it only works when Robert or Joyce performs repeated manual repair.",
    ],
  },
  {
    id: "I",
    label: "I. ShareT / Trello-Sharing Tool Rules",
    summary: "Specific rules for using the ShareT Trello-sharing tool — covering board selection, link generation, and UX standards.",
    whyItMatters: "ShareT is a custom tool with known edge cases. These rules prevent the specific bugs and workflow gaps that have caused problems in the past.",
    icon: ArrowRight,
    color: "border-sky-400 bg-sky-50/30 dark:bg-sky-950/10",
    iconColor: "bg-sky-100 dark:bg-sky-900/30 text-sky-600 dark:text-sky-400",
    rules: [
      "141. ShareT's core purpose is to let external freelancers interact with a Trello card without needing a Trello account.",
      "142. External users should be able to comment and attach files through a shared card link.",
      "143. Board selection must show workspaces because Robert has duplicate board names across workspaces.",
      "144. Generated links must persist after logout, app close, PC restart, and tool updates.",
      "145. Generated links may be temporarily deactivated during development, but they must not be permanently lost.",
      "146. The tool must import and display all Trello checklists, including multiple checklists.",
      "147. The tool must preserve Trello markup and formatting.",
      "148. The tool must show card members.",
      "149. The tool must show exact timestamps, not only '17 days ago.'",
      "150. The tool must load full action history, not only what is visible before 'show all actions.'",
      "151. The tool must import links attached directly to the Trello card.",
      "152. Attachment order should match Trello's order.",
      "153. Attachments must be clickable and open correctly.",
      "154. Comment formatting and attachments should work both ways: Trello to ShareT and ShareT to Trello.",
      "155. The success notification after link generation should not block clicking the link.",
      "156. Auto-copying generated links is nice-to-have, not necessarily core scope.",
      "157. The tool should auto-refresh periodically so freelancers do not work from stale card data.",
      "158. The tool should not introduce an extra credit/payment system unless Robert approves it.",
      "159. The tool should show external commenter names clearly without forcing Trello account creation.",
    ],
  },
  {
    id: "J",
    label: "J. AI / Manus / Prompt-Work Rules",
    summary: "How to use AI tools effectively — covering prompt strategy, session management, and when to use AI vs. when to escalate.",
    whyItMatters: "AI tools are powerful but require structured prompting to produce reliable results. These rules ensure Joyce uses AI to reduce Robert's load, not to generate more work for him to review.",
    icon: Zap,
    color: "border-purple-400 bg-purple-50/30 dark:bg-purple-950/10",
    iconColor: "bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400",
    rules: [
      "160. Before asking AI to build, first ask AI what it needs to know.",
      "161. Project scoping should precede project generation.",
      "162. Joyce should answer the AI questions she can answer and send Robert only the questions that require his judgment.",
      "163. Questions for Robert should be converted into numbered yes/no format where possible.",
      "164. If a question is about Robert's taste, strategic preference, or unknown history, Joyce should mark it for Robert.",
      "165. If a question is not needed for MVP, mark it as not needed now.",
      "166. When one Manus thread is busy, move to another thread. Do not watch AI work.",
      "167. For credit-burn sessions, use large prompts and multiple active threads.",
      "168. For big Manus sessions, use thread-hopping.",
      "169. Manus Max should be used for heavy coding, complex multi-step work, and large enhancements.",
      "170. Manus regular/1.6 should be used for lighter text, letters, analysis, and lower-credit work.",
      "171. Free or low-cost Manus credits should be preserved for urgent legal, lawyer, government, or obligation-related work.",
      "172. Robert's ideas can wait; legal obligations cannot.",
      "173. Metered AI tools require Robert's permission for personal use.",
      "174. Unmetered AI tools may be used more freely if Robert has allowed it and usage limits are not an issue.",
      "175. If using AI for personal work, do not consume metered credits without permission.",
      "176. Use AI to understand unfamiliar legal, technical, or system contexts before briefing a freelancer.",
      "177. Use AI to resolve conflicting instructions into clarification questions.",
      "178. Use AI to turn broad goals into APTLSS plans (via the '🎯 APTLSS Plan' Power-Up button), checklists, and yes/no decision points.",
      "179. Temporary chats can be used for quick processing, but anything important must be saved before closing.",
      "180. AI output is not final unless Joyce verifies it against Robert's actual context.",
    ],
  },
  {
    id: "K",
    label: "K. APTLSS and Planning Rules",
    summary: "Rules for using the APTLSS planning framework — Action Plans, Timelines, and Step Sequences — for complex tasks.",
    whyItMatters: "Complex tasks without a plan create chaos. APTLSS gives Joyce a structured way to break down large work into visible, trackable steps that Robert can review at a glance.",
    icon: Target,
    color: "border-emerald-400 bg-emerald-50/30 dark:bg-emerald-950/10",
    iconColor: "bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400",
    rules: [
      "181. Joyce works better with Action Plans, Timelines, and Step Sequences.",
      "182. APTLSS should be used for large, unclear, or multi-step tasks.",
      "183. APTLSS lives as an AI-generated plan — click '🎯 APTLSS Plan' on any Trello card in the Power-Up to open it. Do NOT write APTLSS as a checklist, in the card description, or as a comment.",
      "184. The APTLSS panel defines: Action (single next step), Plan (strategy), Timeline, Links, Steps (ordered, checkable), Summary, urgency level, next checkpoint, and any Robert decision needed.",
      "185. APTLSS per task is not enough; Joyce also needs a daily cross-task schedule.",
      "186. If several APTLSS tasks are active, Joyce should create a daily time-block plan.",
      "187. For each task, Joyce should know whether it is urgent, important, blocked, waiting, or delegable.",
      "188. For small tasks under three minutes, do them immediately.",
      "189. If a task takes longer, place it in the right Trello card/checklist with a next action.",
      "190. When a task becomes large, break it into subtasks inside the card.",
      "191a. The APTLSS plan can be refreshed at any time by clicking '↻ Refresh' inside the panel. Plans are cached for 4 hours.",
      "191b. Completed steps inside the APTLSS panel can be ticked off directly — progress is saved per card.",
      "191c. The '📋 Copy' button in the APTLSS panel formats the full plan as a Trello comment for sharing with Robert.",
    ],
  },
  {
    id: "L",
    label: "L. Legal, Housing, Police, Insurance, and Dispute Rules",
    summary: "How to handle legal, housing, police, insurance, and dispute matters — the highest-priority category in the system.",
    whyItMatters: "Legal and housing matters can cause severe, irreversible consequences with very little effort from the opposing institution. These rules exist because the cost of getting them wrong is catastrophic.",
    icon: Gavel,
    color: "border-red-400 bg-red-50/30 dark:bg-red-950/10",
    iconColor: "bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400",
    rules: [
      "191. Legal, housing, police, court, and insurance matters require preventive urgency.",
      "192. For these matters, waiting can be dangerous because once procedures pass certain steps, damage may become irreversible.",
      "193. Vivare/housing matters are high priority because losing housing stability threatens both Robert's life and Joyce's work.",
      "194. Police/court matters are high priority because they can cause severe consequences with little effort from the institution.",
      "195. A legal reply on Trello must not sit without acknowledgement.",
      "196. If Robert shares legal replies, Joyce must triage, summarize, and identify next actions.",
      "197. Legal matters should have their own Trello board or clearly structured card system.",
      "198. Each legal case should have one central hub containing parties, documents, deadlines, correspondence, evidence, and next actions.",
      "199. Legal case information must not remain scattered across WhatsApp, Gmail, Drive, Upwork, Manus, and Trello.",
      "200. A lawyer outreach process must be managed as a queue.",
      "201. The first selected lawyer should receive full details and be engaged properly.",
      "202. Backup lawyers should receive polite queue-status emails.",
      "203. If lawyers require phone calls or physical visits, ask whether written/email communication is mandatory or negotiable.",
      "204. If a lawyer refuses written communication and that does not fit Robert's needs, politely decline and record it.",
      "205. Record lawyer responses so Jawad and Robert do not contact unsuitable lawyers again.",
      "206. Do not brief legal freelancers unless Joyce understands the matter well enough.",
      "207. If Joyce does not understand a legal issue, she and Robert must go through it before she instructs a freelancer.",
      "208. For legal matters, written communication is preferred because it creates evidence.",
      "209. If a phone call happens, summarize it in writing afterward.",
      "210. Important legal/admin emails should be copied, linked, or summarized in Trello.",
      "211. If a deadline or ultimatum has passed, the matter becomes priority one until stabilized.",
      "212. For ASR/insurance submissions, sending is not enough; receipt or failure must be confirmed.",
      "213. If email attachments fail, do not keep retrying blindly; find an alternative route.",
      "214. For insurance claims, evidence should include receipts, invoices, bank statements, photos, police reports, and item lists where relevant.",
      "215. Additional costs caused by theft or legal/admin events should be added to the relevant claim card.",
      "216. Evidence involving burglary suspects must be preserved with source, timestamp, and original copies.",
      "217. For fake-product or marketplace disputes, preserve the product evidence, seller communication, platform messages, and police/threat evidence.",
    ],
  },
  {
    id: "M",
    label: "M. Evidence Preservation Rules",
    summary: "Rules for capturing, storing, and linking evidence before it can be deleted or lost.",
    whyItMatters: "Evidence that is not preserved immediately may be gone forever. Screenshots, recordings, and documents must be saved before hostile parties can delete them.",
    icon: Camera,
    color: "border-pink-400 bg-pink-50/30 dark:bg-pink-950/10",
    iconColor: "bg-pink-100 dark:bg-pink-900/30 text-pink-600 dark:text-pink-400",
    rules: [
      "218. If evidence may expire, disappear, be deleted, or become inaccessible, preserving it becomes priority one.",
      "219. ScreenPal/Loom/video evidence must be downloaded before deadlines.",
      "220. Backups should exist in more than one place when evidence is important.",
      "221. Videos should be downloaded, stored, and uploaded to the agreed destination when needed.",
      "222. Evidence should be linked to the relevant Trello card.",
      "223. Do not rely on platforms that can change storage limits without warning.",
      "224. For large evidence tasks, maintain a progress tracker: total, downloaded, uploaded, failed, remaining, deadline.",
      "225. Original files should be preserved before editing or compressing.",
      "226. Screenshots should be stored with date and context.",
      "227. If evidence belongs to a legal/insurance/police matter, treat it as sensitive and traceable.",
    ],
  },
  {
    id: "N",
    label: "N. Google Drive and File-Management Rules",
    summary: "Standards for naming, organizing, and linking files in Google Drive so they can always be found when needed.",
    whyItMatters: "A file saved in the wrong folder or with an unclear name is effectively lost. These rules ensure the file system supports legal, operational, and audit needs.",
    icon: Search,
    color: "border-lime-400 bg-lime-50/30 dark:bg-lime-950/10",
    iconColor: "bg-lime-100 dark:bg-lime-900/30 text-lime-600 dark:text-lime-400",
    rules: [
      "228. A task is not complete until the file is saved in the correct Drive folder and linked in Trello.",
      "229. Google Drive structure must be logical, named clearly, and consistent.",
      "230. Scattered files create legal and operational risk.",
      "231. Wrong folder placement is not a minor issue if the document must be found later.",
      "232. Receipts and invoices should be split and stored per receipt/invoice where appropriate.",
      "233. Drive folders should match Trello/legal/project structures where possible.",
      "234. Documents should be named so that Robert or Joyce can identify them later without opening each file.",
      "235. If a freelancer is sorting Drive, they need enough access to work, but not unnecessary access.",
      "236. Drive access should be temporary for freelancers.",
      "237. Files provided by email should be downloaded/saved to Drive if relevant to an ongoing matter.",
      "238. If attachments are too large, use a proper upload route instead of repeated failed email attempts.",
      "239. If Drive and Trello disagree, update both or link them clearly.",
    ],
  },
  {
    id: "O",
    label: "O. Account Access, LastPass, and Security Rules",
    summary: "How to manage account access, LastPass entries, and security so Joyce is never blocked by a missing login.",
    whyItMatters: "Missing account access is one of the most common causes of task delays. These rules ensure every recurring account is documented, accessible, and secure.",
    icon: Shield,
    color: "border-slate-400 bg-slate-50/30 dark:bg-slate-950/10",
    iconColor: "bg-slate-100 dark:bg-slate-900/30 text-slate-600 dark:text-slate-400",
    rules: [
      "240. Joyce needs LastPass access to recurring work accounts, otherwise tasks become blocked.",
      "241. Recurring accounts must have complete LastPass entries.",
      "242. Each account entry should include login URL, username/email, password, MFA method, recovery route, and notes.",
      "243. If a verification code is delayed, verify the email route, check spam if possible, then switch tasks while waiting.",
      "244. Do not sit idle waiting for a code.",
      "245. If access fails, document the exact issue.",
      "246. If a platform uses off-platform credentials, record the flow clearly.",
      "247. Account-sharing and third-party access should be deliberate, not casual.",
      "248. If a freelancer no longer needs access, remove it.",
      "249. If there is conflict with a freelancer, remove access before confrontation.",
      "250. Do not give broad account access when folder-specific or view-only access is enough.",
    ],
  },
  {
    id: "P",
    label: "P. Client and Business Rules",
    summary: "How to handle client relationships, deliverables, and business communications to protect long-term value.",
    whyItMatters: "Good clients are long-term assets. These rules ensure that client-facing work meets the standard required for government, legal, and client review — not just internal use.",
    icon: BookOpen,
    color: "border-emerald-400 bg-emerald-50/30 dark:bg-emerald-950/10",
    iconColor: "bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400",
    rules: [
      "251. Good clients are long-term assets, not one-off transactions.",
      "252. If a client may bring recurring work, quality and communication must reflect that value.",
      "253. Client-facing deliverables must be accurate enough for client and government review.",
      "254. Do not assume a patient client will remain patient indefinitely.",
      "255. If a client has waited too long, asking for more money becomes risky.",
      "256. For Dutch clients, delivery and task completion often matter more than personal relationship.",
      "257. If failure could cost a major project, the task becomes high priority.",
      "258. Robert should not promise client-facing quality unless the underlying work is accurate.",
      "259. Joyce should understand the commercial consequences of client-facing delays.",
      "260. Recurring work helps fund Joyce, tools, freelancers, and Robert's broader goals.",
    ],
  },
  {
    id: "Q",
    label: "Q. Bike Shed / Design-Project Rules",
    summary: "Accuracy and documentation standards for design and permit drawings — where real-world dimensions always override aesthetics.",
    whyItMatters: "Permit drawings that don't match reality can cause legal and financial problems. Accuracy is non-negotiable when drawings are submitted to clients or government bodies.",
    icon: Home,
    color: "border-amber-400 bg-amber-50/30 dark:bg-amber-950/10",
    iconColor: "bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400",
    rules: [
      "261. Accuracy beats aesthetics.",
      "262. For permit/client/government drawings, real-world dimensions and property conditions are the truth.",
      "263. Do not modify reality to make a render look cleaner.",
      "264. The drawing must match Google Maps, photos, dimensions, slopes, stairs, pathways, boundaries, and elevation differences.",
      "265. Old videos become invalid if newer written corrections override them.",
      "266. The latest written correction document is the source of truth.",
      "267. Do not mix old renders with new renders if they contain different edits.",
      "268. Do not export all final high-quality angles until the design itself is final.",
      "269. All required angles must be provided, not only one or two.",
      "270. If vegetation blocks the structure, provide both obstructed and unobstructed comparison views.",
      "271. If the side hedge blocks permit evaluation, remove enough of it in one view to show the full shed.",
      "272. If a house model is only a placeholder, the designer should still search for a better Dutch-style model within a fixed time window.",
      "273. Tool limitations are not valid excuses if the tool cannot produce accurate dimensions.",
      "274. If the software cannot do accurate technical work, the software is unsuitable.",
      "275. Before the designer edits, Joyce must verify that he understands the correction document.",
      "276. If the designer repeatedly misunderstands, Joyce should sit down with him and confirm point-by-point.",
      "277. If corrections affect the 3D model, the blueprint measurements must also be updated.",
      "278. If the project reaches Robert's final boundary, the next version should be treated as client-facing, not another draft for Robert to fix.",
    ],
  },
  {
    id: "R",
    label: "R. Work Infrastructure Rules",
    summary: "Rules for maintaining the physical and digital infrastructure Joyce needs to work reliably — power, internet, equipment.",
    whyItMatters: "Infrastructure failures are operational problems, not personal inconveniences. A power outage that blocks communication affects Robert's work too.",
    icon: Laptop,
    color: "border-cyan-400 bg-cyan-50/30 dark:bg-cyan-950/10",
    iconColor: "bg-cyan-100 dark:bg-cyan-900/30 text-cyan-600 dark:text-cyan-400",
    rules: [
      "279. Infrastructure limitations are operational problems, not merely personal inconveniences.",
      "280. UPS was priority because power outages blocked communication and work.",
      "281. During power outages, the UPS should be used first to notify Robert and preserve communication.",
      "282. Do not fully drain the UPS; keep enough power for phone communication.",
      "283. Dual screens are expected to improve context handling and productivity.",
      "284. If a tool or hardware investment improves reliability, Joyce should report the effect.",
      "285. If hardware limitations are slowing output, Joyce should raise it as an operational issue.",
      "286. A dedicated work WhatsApp account or setup is useful only if it is monitored consistently.",
      "287. Workspace setup should support focus, clarity, and quick switching between tasks.",
    ],
  },
  {
    id: "S",
    label: "S. Personal Performance and Accountability Rules",
    summary: "How Joyce measures, reports, and improves her own performance — covering accountability, growth, and self-assessment.",
    whyItMatters: "Trustworthiness is Joyce's biggest strength. These rules define how that trust is maintained and grown through measurable, visible improvement rather than vague promises.",
    icon: Target,
    color: "border-pink-400 bg-pink-50/30 dark:bg-pink-950/10",
    iconColor: "bg-pink-100 dark:bg-pink-900/30 text-pink-600 dark:text-pink-400",
    rules: [
      "288. Joyce's biggest strength is trustworthiness; the next development area is autonomous effectiveness.",
      "289. Joyce should make progress visible enough that Robert can notice it without asking.",
      "290. Growth must be measurable, not only promised.",
      "291. 'I will improve communication' is too vague; 'I will update 2-5 Trello cards daily for 4 weeks' is measurable.",
      "292. Joyce should define indicators for her own improvement and consistency.",
      "293. If Joyce experiences a dip, she should inform Robert before it becomes operational damage.",
      "294. Relapses in responsiveness must be treated as a system problem to solve, not only a personal intention to improve.",
      "295. Joyce should consult a trusted person or use AI to build consistency systems if needed.",
      "296. Robert may develop a baseline, merit, and demerit system.",
      "297. Baseline means no recurring preventable failures.",
      "298. Above-baseline work should be tied to measurable burden reduction, not merely doing more.",
      "299. Below-baseline work may eventually affect pay if agreed and formalized.",
      "300. Bonus/increase discussions should consider accuracy, speed, independence, progress, and reduced Robert workload.",
      "301. The key question is: does Robert have to do more or less work than before?",
      "302. Joyce should not wait for Robert to define the whole performance system alone; she should contribute thoughts.",
    ],
  },
  {
    id: "T",
    label: "T. Crunch-Time Rules",
    summary: "How to handle rare high-pressure periods when multiple deadlines collide and normal routines must be suspended.",
    whyItMatters: "Crunch time without structure becomes chaos. These rules ensure that even under extreme pressure, work is prioritized correctly and Robert is never left without a status update.",
    icon: Clock,
    color: "border-red-400 bg-red-50/30 dark:bg-red-950/10",
    iconColor: "bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400",
    rules: [
      "303. Rare 20–24 hour crunch periods may happen when many deadlines collide.",
      "304. Crunch work should be structured, not chaotic.",
      "305. If Joyce needs sleep during crunch time, she must hand over status before leaving.",
      "306. A suggested crunch rhythm is 20 hours work, 4 hours sleep, then continue if necessary.",
      "307. During crunch, legal obligations and irreversible-loss items outrank idea development.",
      "308. If Robert expects Joyce to stay available for a long session, clarify availability and handoff points.",
      "309. Do not disappear during a crunch without a status note.",
      "310. If multiple AI threads are running, organize tabs and workspaces so the session remains manageable.",
    ],
  },
  {
    id: "U",
    label: "U. Browser/Tab/Project-Organization Rules",
    summary: "How to organize browser tabs and desktops by project to prevent context-switching and project mixing.",
    whyItMatters: "Tab chaos leads to missed updates and project mixing. Grouping tabs by project ensures Joyce can switch context cleanly without losing track of what belongs where.",
    icon: Search,
    color: "border-indigo-400 bg-indigo-50/30 dark:bg-indigo-950/10",
    iconColor: "bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400",
    rules: [
      "311. Group tabs by project.",
      "312. Each project tab group should contain the intranet page, Manus thread, GitHub repo, Trello card, Drive folder, and relevant notes.",
      "313. Use separate desktops if tab groups are not enough.",
      "314. Do not let tab spam cause project mixing.",
      "315. If multiple projects are active, clearly define ownership: Robert handles X, Joyce handles Y.",
      "316. If Joyce cannot track multiple projects, she should work one product at a time or group them strictly.",
      "317. When creating many Manus threads, maintain a tracking list so work is not duplicated.",
    ],
  },
  {
    id: "V",
    label: "V. Payment and Finance-Administration Rules",
    summary: "Rules for recording payment changes, equipment costs, and financial agreements between Robert and Joyce.",
    whyItMatters: "Financial agreements that are not documented in writing create disputes. These rules ensure every payment change, deduction, and cost-sharing arrangement is recorded clearly.",
    icon: DollarSign,
    color: "border-green-400 bg-green-50/30 dark:bg-green-950/10",
    iconColor: "bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400",
    rules: [
      "318. Payment changes should be recorded clearly.",
      "319. If Robert sends early payment, note the next regular payment date.",
      "320. If Joyce buys work equipment with Robert's support, clarify total cost, Joyce contribution, Robert contribution, and purpose.",
      "321. If Joyce incurs travel cost due to a freelancer failing to deliver, Robert may deduct that from the freelancer's compensation if agreed.",
      "322. Do not mix personal and project funds without clarity.",
      "323. If a tool has metered costs, permission is required before using it for non-Robert work.",
    ],
  },
  {
    id: "W",
    label: "W. Medical / Diagnosis / Dutch-System Research Rules",
    summary: "How to navigate the Dutch healthcare system when researching medical or diagnosis matters on Robert's behalf.",
    whyItMatters: "The Dutch referral system has specific rules that, if ignored, lead to wasted calls and dead ends. Understanding the process first saves significant time and avoids frustrating providers.",
    icon: Heart,
    color: "border-rose-400 bg-rose-50/30 dark:bg-rose-950/10",
    iconColor: "bg-rose-100 dark:bg-rose-900/30 text-rose-600 dark:text-rose-400",
    rules: [
      "324. Before contacting providers in the Netherlands, understand the referral system first.",
      "325. For diagnosis matters, first determine whether GP referral is required.",
      "326. Do not ask for GP contact details unless the process requires it and the reason is understood.",
      "327. When contacting doctors/providers, ask whether they can be recommended to the GP for referral.",
      "328. All medical/legal-adjacent communication should be written and traceable.",
      "329. Freelancers working on Dutch systems should receive enough explanation to avoid running in circles.",
    ],
  },
  {
    id: "X",
    label: "X. Written-Communication and Paper-Trail Rules",
    summary: "Why written communication is always preferred over calls, and how to create a traceable paper trail for every important interaction.",
    whyItMatters: "Calls are hard to prove. Written records protect Robert in legal, insurance, and dispute situations. These rules ensure that every important communication leaves a trace.",
    icon: Mail,
    color: "border-slate-400 bg-slate-50/30 dark:bg-slate-950/10",
    iconColor: "bg-slate-100 dark:bg-slate-900/30 text-slate-600 dark:text-slate-400",
    rules: [
      "330. Written communication is preferred over calls for legal, government, insurance, client, and dispute matters.",
      "331. Calls are harder to prove; emails and texts create traceability.",
      "332. If a call is unavoidable, summarize the result in writing.",
      "333. Important communications should CC Robert/Joyce where appropriate.",
      "334. If a freelancer communicates externally, Robert/Joyce should remain in the loop.",
      "335. Sensitive or high-risk emails should be approved before sending unless authority was already given.",
      "336. A paper trail should exist before escalating disputes.",
      "337. Screenshots should be taken before a hostile party deletes or edits information.",
    ],
  },
  {
    id: "Y",
    label: "Y. Work-Quality Mindset Rules",
    summary: "The mindset standards that define what 'good enough' actually means — and why 'still fine' is not the same as 'done'.",
    whyItMatters: "Work that requires Robert to inspect and correct is not finished work. These rules define the quality bar: would this make Robert feel relieved, or would he still need to check it?",
    icon: CheckCircle,
    color: "border-violet-400 bg-violet-50/30 dark:bg-violet-950/10",
    iconColor: "bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400",
    rules: [
      "338. Do not accept 'this is still fine' if it does not meet Robert's actual standard.",
      "339. Ask: would this make Robert feel relieved, or would he still need to inspect and correct it?",
      "340. If the answer is that Robert still needs to inspect heavily, the handover is not yet good enough.",
      "341. Joyce should develop a sharp eye for shortcomings.",
      "342. Use AI to increase understanding, not to avoid responsibility.",
      "343. If Joyce knows only 1%, she should use AI to get to enough understanding to act responsibly.",
      "344. Respect opens doors; coherent, complete, informed communication creates respect.",
      "345. Do not treat high standards as optional.",
      "346. If Robert exports a standard into writing, use it as the operating standard.",
      "347. If a written standard exists, test against it.",
      "348. If a standard is unclear, ask for clarification or use AI to create a checklist.",
    ],
  },
  {
    id: "Z",
    label: "Z. Simple Best Dos Already Identified",
    summary: "A concise list of the most important behaviours already identified as high-value — the essentials distilled into simple, memorable rules.",
    whyItMatters: "These are the rules that have already proven their worth in practice. When in doubt, return to these basics — they cover the most common failure modes in one place.",
    icon: Star,
    color: "border-yellow-400 bg-yellow-50/30 dark:bg-yellow-950/10",
    iconColor: "bg-yellow-100 dark:bg-yellow-900/30 text-yellow-600 dark:text-yellow-400",
    rules: [
      "349. What can be done in 3 minutes, do it now.",
      "350. Say what you do, do what you say.",
      "351. Do not assume silently.",
      "352. If you need Robert, frame the question for yes/no.",
      "353. Make progress visible.",
      "354. If blocked, move another task forward.",
      "355. If it matters, put it in Trello.",
      "356. If it is urgent, send the Trello link on WhatsApp.",
      "357. If evidence can be lost, preserve it first.",
      "358. If a freelancer becomes risky, remove access first.",
      "359. If the task affects legal/housing/court/police/insurance, treat it as preventive defense.",
      "360. If Robert feels burdened, the system needs improvement, not only more effort.",
    ],
  },
];
