CREATE TABLE `daily_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dateKey` varchar(16) NOT NULL,
	`scheduleJson` text NOT NULL,
	`dailySummary` text,
	`topPriority` varchar(512),
	`totalScheduledMinutes` int NOT NULL DEFAULT 0,
	`robertItemsCount` int NOT NULL DEFAULT 0,
	`autoGenerated` boolean NOT NULL DEFAULT true,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `daily_plans_id` PRIMARY KEY(`id`),
	CONSTRAINT `daily_plans_dateKey_unique` UNIQUE(`dateKey`)
);
