export const APTLSS_CARD_STATES = [
  "NEW_UNTRIAGED",
  "READY_TO_START",
  "IN_PROGRESS",
  "WAITING_FOR_JOYCE",
  "WAITING_FOR_ROBERT",
  "WAITING_FOR_EXTERNAL_PARTY",
  "BLOCKED_BY_OTHER_CARD",
  "STALLED",
  "OVERDUE",
  "READY_FOR_REVIEW",
  "READY_FOR_DONE",
  "DONE_CONFIRMED",
  "NEEDS_RESTRUCTURING",
  "NEEDS_ARCHIVE",
] as const;

export type AptlssCardStateValue = (typeof APTLSS_CARD_STATES)[number];
