/**
 * APTLSS DB helpers — store and retrieve AI-generated action plans per Trello card.
 */
import { getDb } from "./db";
import { aptlssPlans, InsertAptlssPlan, dailyPlans, InsertDailyPlan } from "../drizzle/schema";
import { eq, desc } from "drizzle-orm";

// ─── APTLSS Card Plans ────────────────────────────────────────────────────────

/** Upsert (insert or replace) an APTLSS plan for a card. */
export async function upsertAptlssPlan(plan: InsertAptlssPlan): Promise<void> {
  const db = await getDb();
  if (!db) return;
  // Delete any existing plan for this card first, then insert fresh
  await db.delete(aptlssPlans).where(eq(aptlssPlans.cardId, plan.cardId));
  await db.insert(aptlssPlans).values(plan);
}

/** Get the most recent APTLSS plan for a card (null if none). */
export async function getAptlssPlan(cardId: string): Promise<(typeof aptlssPlans.$inferSelect) | null> {
  const db = await getDb();
  if (!db) return null;
  const rows = await db
    .select()
    .from(aptlssPlans)
    .where(eq(aptlssPlans.cardId, cardId))
    .orderBy(desc(aptlssPlans.generatedAt))
    .limit(1);
  return rows[0] ?? null;
}

/** Get all stored APTLSS plans (for admin/debug view). */
export async function getAllAptlssPlans(): Promise<(typeof aptlssPlans.$inferSelect)[]> {
  const db = await getDb();
  if (!db) return [];
  return await db.select().from(aptlssPlans).orderBy(desc(aptlssPlans.generatedAt));
}

// ─── Daily Plans ──────────────────────────────────────────────────────────────

/** Upsert (insert or replace) a daily plan for a given date. */
export async function upsertDailyPlan(plan: InsertDailyPlan): Promise<void> {
  const db = await getDb();
  if (!db) return;
  await db
    .insert(dailyPlans)
    .values(plan)
    .onDuplicateKeyUpdate({
      set: {
        scheduleJson: plan.scheduleJson,
        dailySummary: plan.dailySummary ?? null,
        topPriority: plan.topPriority ?? null,
        totalScheduledMinutes: plan.totalScheduledMinutes ?? 0,
        robertItemsCount: plan.robertItemsCount ?? 0,
        autoGenerated: plan.autoGenerated ?? true,
        generatedAt: new Date(),
      },
    });
}

/** Get the most recently generated daily plan. */
export async function getLatestDailyPlan(): Promise<(typeof dailyPlans.$inferSelect) | null> {
  const db = await getDb();
  if (!db) return null;
  const rows = await db
    .select()
    .from(dailyPlans)
    .orderBy(desc(dailyPlans.generatedAt))
    .limit(1);
  return rows[0] ?? null;
}

/** Get a daily plan by ISO date key (e.g. "2026-05-27"). */
export async function getDailyPlanByDate(dateKey: string): Promise<(typeof dailyPlans.$inferSelect) | null> {
  const db = await getDb();
  if (!db) return null;
  const rows = await db
    .select()
    .from(dailyPlans)
    .where(eq(dailyPlans.dateKey, dateKey))
    .limit(1);
  return rows[0] ?? null;
}
